name: publish-v3

on:
  workflow_run:
    workflows: [ci]
    branches: [v3]
    types: [completed]

env:
  TURBO_TOKEN: ${{ secrets.VERCEL_STORYBOOK_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

concurrency: publish_workflow

jobs:
  # Publish the public packages to npm
  npm:
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 50
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout code repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: 'v3'

      - name: install and audit
        uses: ./support/actions/pnpm

      - name: build project
        run: pnpm build

      - name: publish npm release
        run: |
          pnpm release:beta

      - name: parse changelog for @remirror/react
        id: changelog_remirror_react
        uses: ocavue/changelog-parser-action@v1
        with:
          filePath: 'packages/remirror__react/CHANGELOG.md'

      - name: create release for @remirror/react
        uses: ncipollo/release-action@v1
        with:
          commit: v3-beta
          tag: '@remirror/react@${{ fromJSON(steps.changelog_remirror_react.outputs.parsed).versions[0].version }}'
          body: '${{ fromJSON(steps.changelog_remirror_react.outputs.parsed).versions[0].body }}'
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: parse changelog for @remirror/pm
        id: changelog_remirror_pm
        uses: ocavue/changelog-parser-action@v1
        with:
          filePath: 'packages/remirror__pm/CHANGELOG.md'

      - name: create release for @remirror/pm
        uses: ncipollo/release-action@v1
        with:
          commit: v3-beta
          tag: '@remirror/pm@${{ fromJSON(steps.changelog_remirror_pm.outputs.parsed).versions[0].version }}'
          body: '${{ fromJSON(steps.changelog_remirror_pm.outputs.parsed).versions[0].body }}'
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      # make sure that `remirror` is the last one so that it can at the top of the release list
      - name: parse changelog for remirror
        id: changelog_remirror
        uses: ocavue/changelog-parser-action@v1
        with:
          filePath: 'packages/remirror/CHANGELOG.md'

      - name: create release for remirror
        uses: ncipollo/release-action@v1
        with:
          commit: v3-beta
          tag: 'remirror@${{ fromJSON(steps.changelog_remirror.outputs.parsed).versions[0].version }}'
          body: '${{ fromJSON(steps.changelog_remirror.outputs.parsed).versions[0].body }}'
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
