name: storybook

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - v1
      - main

env:
  TURBO_TOKEN: ${{ secrets.VERCEL_STORYBOOK_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  deploy_docs:
    timeout-minutes: 50
    runs-on: ubuntu-latest

    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install and audit
        uses: ./support/actions/pnpm

      - name: build storybook
        run: |
          export STORYBOOK_BUILD_TIME=$(date +"%Y-%m-%dT%H:%M:%S%z")
          export STORYBOOK_GIT_SHA=$GITHUB_SHA
          export STORYBOOK_GIT_REF=$GITHUB_REF
          export NODE_OPTIONS=--max_old_space_size=4096
          pnpm storybook:build

      - name: deploy storybook for pull request
        uses: amondnet/vercel-action@v25.1.1
        if: github.ref != 'refs/heads/main' && github.event.pull_request.head.repo.full_name == github.repository # don't run this job from a fork repository
        with:
          working-directory: ./packages/storybook-react/storybook-static
          vercel-token: ${{ secrets.VERCEL_STORYBOOK_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_STORYBOOK_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID }}

          # necessary for comment on pull request.
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias-domains: |
            pr{{PR_NUMBER}}-remirror-ocavue.vercel.app

      - name: deploy storybook for production
        uses: amondnet/vercel-action@v25.1.1
        if: github.ref == 'refs/heads/main'
        with:
          working-directory: ./packages/storybook-react/storybook-static
          vercel-token: ${{ secrets.VERCEL_STORYBOOK_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_STORYBOOK_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID }}

          # deploy to production environment (https://remirror.vercel.app)
          vercel-args: '--prod'
